In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import preprocessing


data = pd.read_csv("Lung_cancer.csv")
print(data)

    GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0        M   69        1               2        2              1   
1        M   74        2               1        1              1   
2        F   59        1               1        1              2   
3        M   63        2               2        2              1   
4        F   63        1               2        1              1   
..     ...  ...      ...             ...      ...            ...   
304      F   56        1               1        1              2   
305      M   70        2               1        1              1   
306      M   58        2               1        1              1   
307      M   67        2               1        2              1   
308      M   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2       

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   GENDER                 309 non-null    object
 1   AGE                    309 non-null    int64 
 2   SMOKING                309 non-null    int64 
 3   YELLOW_FINGERS         309 non-null    int64 
 4   ANXIETY                309 non-null    int64 
 5   PEER_PRESSURE          309 non-null    int64 
 6   CHRONIC DISEASE        309 non-null    int64 
 7   FATIGUE                309 non-null    int64 
 8   ALLERGY                309 non-null    int64 
 9   WHEEZING               309 non-null    int64 
 10  ALCOHOL CONSUMING      309 non-null    int64 
 11  COUGHING               309 non-null    int64 
 12  SHORTNESS OF BREATH    309 non-null    int64 
 13  SWALLOWING DIFFICULTY  309 non-null    int64 
 14  CHEST PAIN             309 non-null    int64 
 15  LUNG_CANCER            

In [3]:
data.describe()

AGE     SMOKING  YELLOW_FINGERS     ANXIETY  PEER_PRESSURE  \
count  309.000000  309.000000      309.000000  309.000000     309.000000   
mean    62.673139    1.563107        1.569579    1.498382       1.501618   
std      8.210301    0.496806        0.495938    0.500808       0.500808   
min     21.000000    1.000000        1.000000    1.000000       1.000000   
25%     57.000000    1.000000        1.000000    1.000000       1.000000   
50%     62.000000    2.000000        2.000000    1.000000       2.000000   
75%     69.000000    2.000000        2.000000    2.000000       2.000000   
max     87.000000    2.000000        2.000000    2.000000       2.000000   

       CHRONIC DISEASE    FATIGUE     ALLERGY     WHEEZING  ALCOHOL CONSUMING  \
count       309.000000  309.000000  309.000000  309.000000         309.000000   
mean          1.504854    1.673139    1.556634    1.556634           1.556634   
std           0.500787    0.469827    0.497588    0.497588           0.497588   
min           1.000000    1.000000    1.000000    1.000000           1.000000   
25%           1.000000    1.000000    1.000000    1.000000           1.000000   
50%           2.000000    2.000000    2.000000    2.000000           2.000000   
75%           2.000000    2.000000    2.000000    2.000000           2.000000   
max           2.000000    2.000000    2.000000    2.000000           2.000000   

         COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  
count  309.000000           309.000000             309.000000  309.000000  
mean     1.579288             1.640777               1.469256    1.556634  
std      0.494474             0.480551               0.499863    0.497588  
min      1.000000             1.000000               1.000000    1.000000  
25%      1.000000             1.000000               1.000000    1.000000  
50%      2.000000             2.000000               1.000000    2.000000  
75%      2.000000             2.000000               2.000000    2.000000  
max      2.000000             2.000000               2.000000    2.000000

In [4]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
data['GENDER']=le.fit_transform(data['GENDER'])
data['LUNG_CANCER']=le.fit_transform(data['LUNG_CANCER'])
data['SMOKING']=le.fit_transform(data['SMOKING'])
data['YELLOW_FINGERS']=le.fit_transform(data['YELLOW_FINGERS'])
data['ANXIETY']=le.fit_transform(data['ANXIETY'])
data['PEER_PRESSURE']=le.fit_transform(data['PEER_PRESSURE'])
data['CHRONIC DISEASE']=le.fit_transform(data['CHRONIC DISEASE'])
data['FATIGUE ']=le.fit_transform(data['FATIGUE '])
data['ALLERGY ']=le.fit_transform(data['ALLERGY '])
data['WHEEZING']=le.fit_transform(data['WHEEZING'])
data['ALCOHOL CONSUMING']=le.fit_transform(data['ALCOHOL CONSUMING'])
data['COUGHING']=le.fit_transform(data['COUGHING'])
data['SHORTNESS OF BREATH']=le.fit_transform(data['SHORTNESS OF BREATH'])
data['SWALLOWING DIFFICULTY']=le.fit_transform(data['SWALLOWING DIFFICULTY'])
data['CHEST PAIN']=le.fit_transform(data['CHEST PAIN'])
data['LUNG_CANCER']=le.fit_transform(data['LUNG_CANCER'])


In [5]:
data

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        0               1        1              0   
1         1   74        1               0        0              0   
2         0   59        0               0        0              1   
3         1   63        1               1        1              0   
4         0   63        0               1        0              0   
..      ...  ...      ...             ...      ...            ...   
304       0   56        0               0        0              1   
305       1   70        1               0        0              0   
306       1   58        1               0        0              0   
307       1   67        1               0        1              0   
308       1   62        0               0        0              1   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  0         1         0         1                  1   
1                  1         1         1         0                  0   
2                  0         1         0         1                  0   
3                  0         0         0         0                  1   
4                  0         0         0         1                  0   
..               ...       ...       ...       ...                ...   
304                1         1         0         0                  1   
305                0         1         1         1                  1   
306                0         0         1         1                  1   
307                0         1         1         0                  1   
308                0         1         1         1                  1   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           1                    1                      1           1   
1           0                    1                      1           1   
2           1                    1                      0           1   
3           0                    0                      1           1   
4           1                    1                      0           0   
..        ...                  ...                    ...         ...   
304         1                    1                      1           0   
305         1                    1                      0           1   
306         1                    0                      0           1   
307         1                    1                      0           1   
308         0                    0                      1           0   

     LUNG_CANCER  
0              1  
1              1  
2              0  
3              0  
4              0  
..           ...  
304            1  
305            1  
306            1  
307            1  
308            1  

[309 rows x 16 columns]

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309 entries, 0 to 308
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   GENDER                 309 non-null    int32
 1   AGE                    309 non-null    int64
 2   SMOKING                309 non-null    int64
 3   YELLOW_FINGERS         309 non-null    int64
 4   ANXIETY                309 non-null    int64
 5   PEER_PRESSURE          309 non-null    int64
 6   CHRONIC DISEASE        309 non-null    int64
 7   FATIGUE                309 non-null    int64
 8   ALLERGY                309 non-null    int64
 9   WHEEZING               309 non-null    int64
 10  ALCOHOL CONSUMING      309 non-null    int64
 11  COUGHING               309 non-null    int64
 12  SHORTNESS OF BREATH    309 non-null    int64
 13  SWALLOWING DIFFICULTY  309 non-null    int64
 14  CHEST PAIN             309 non-null    int64
 15  LUNG_CANCER            309 non-null    i

In [7]:
print(data.corr()["LUNG_CANCER"].abs().sort_values(ascending=False))

LUNG_CANCER              1.000000
ALLERGY                  0.327766
ALCOHOL CONSUMING        0.288533
SWALLOWING DIFFICULTY    0.259730
WHEEZING                 0.249300
COUGHING                 0.248570
CHEST PAIN               0.190451
PEER_PRESSURE            0.186388
YELLOW_FINGERS           0.181339
FATIGUE                  0.150673
ANXIETY                  0.144947
CHRONIC DISEASE          0.110891
AGE                      0.089465
GENDER                   0.067254
SHORTNESS OF BREATH      0.060738
SMOKING                  0.058179
Name: LUNG_CANCER, dtype: float64


In [8]:
data_new = data.drop(['GENDER', 'AGE', 'SMOKING', 'SHORTNESS OF BREATH'], axis = 1)
data_new

YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  FATIGUE   \
0                 1        1              0                0         1   
1                 0        0              0                1         1   
2                 0        0              1                0         1   
3                 1        1              0                0         0   
4                 1        0              0                0         0   
..              ...      ...            ...              ...       ...   
304               0        0              1                1         1   
305               0        0              0                0         1   
306               0        0              0                0         0   
307               0        1              0                0         1   
308               0        0              1                0         1   

     ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY  \
0           0         1                  1         1                      1   
1           1         0                  0         0                      1   
2           0         1                  0         1                      0   
3           0         0                  1         0                      1   
4           0         1                  0         1                      0   
..        ...       ...                ...       ...                    ...   
304         0         0                  1         1                      1   
305         1         1                  1         1                      0   
306         1         1                  1         1                      0   
307         1         0                  1         1                      0   
308         1         1                  1         0                      1   

     CHEST PAIN  LUNG_CANCER  
0             1            1  
1             1            1  
2             1            0  
3             1            0  
4             0            0  
..          ...          ...  
304           0            1  
305           1            1  
306           1            1  
307           1            1  
308           0            1  

[309 rows x 12 columns]

In [9]:
cn = data_new.corr()
cn

YELLOW_FINGERS   ANXIETY  PEER_PRESSURE  \
YELLOW_FINGERS               1.000000  0.565829       0.323083   
ANXIETY                      0.565829  1.000000       0.216841   
PEER_PRESSURE                0.323083  0.216841       1.000000   
CHRONIC DISEASE              0.041122 -0.009678       0.048515   
FATIGUE                     -0.118058 -0.188538       0.078148   
ALLERGY                     -0.144300 -0.165750      -0.081800   
WHEEZING                    -0.078515 -0.191807      -0.068771   
ALCOHOL CONSUMING           -0.289025 -0.165750      -0.159973   
COUGHING                    -0.012640 -0.225644      -0.089019   
SWALLOWING DIFFICULTY        0.345904  0.489403       0.366590   
CHEST PAIN                  -0.104829 -0.113634      -0.094828   
LUNG_CANCER                  0.181339  0.144947       0.186388   

                       CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  \
YELLOW_FINGERS                0.041122 -0.118058 -0.144300 -0.078515   
ANXIETY                      -0.009678 -0.188538 -0.165750 -0.191807   
PEER_PRESSURE                 0.048515  0.078148 -0.081800 -0.068771   
CHRONIC DISEASE               1.000000 -0.110529  0.106386 -0.049967   
FATIGUE                      -0.110529  1.000000  0.003056  0.141937   
ALLERGY                       0.106386  0.003056  1.000000  0.173867   
WHEEZING                     -0.049967  0.141937  0.173867  1.000000   
ALCOHOL CONSUMING             0.002150 -0.191377  0.344339  0.265659   
COUGHING                     -0.175287  0.146856  0.189524  0.374265   
SWALLOWING DIFFICULTY         0.075176 -0.132790 -0.061508  0.069027   
CHEST PAIN                   -0.036938 -0.010832  0.239433  0.147640   
LUNG_CANCER                   0.110891  0.150673  0.327766  0.249300   

                       ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY  \
YELLOW_FINGERS                 -0.289025 -0.012640               0.345904   
ANXIETY                        -0.165750 -0.225644               0.489403   
PEER_PRESSURE                  -0.159973 -0.089019               0.366590   
CHRONIC DISEASE                 0.002150 -0.175287               0.075176   
FATIGUE                        -0.191377  0.146856              -0.132790   
ALLERGY                         0.344339  0.189524              -0.061508   
WHEEZING                        0.265659  0.374265               0.069027   
ALCOHOL CONSUMING               1.000000  0.202720              -0.009294   
COUGHING                        0.202720  1.000000              -0.157586   
SWALLOWING DIFFICULTY          -0.009294 -0.157586               1.000000   
CHEST PAIN                      0.331226  0.083958               0.069027   
LUNG_CANCER                     0.288533  0.248570               0.259730   

                       CHEST PAIN  LUNG_CANCER  
YELLOW_FINGERS          -0.104829     0.181339  
ANXIETY                 -0.113634     0.144947  
PEER_PRESSURE           -0.094828     0.186388  
CHRONIC DISEASE         -0.036938     0.110891  
FATIGUE                 -0.010832     0.150673  
ALLERGY                  0.239433     0.327766  
WHEEZING                 0.147640     0.249300  
ALCOHOL CONSUMING        0.331226     0.288533  
COUGHING                 0.083958     0.248570  
SWALLOWING DIFFICULTY    0.069027     0.259730  
CHEST PAIN               1.000000     0.190451  
LUNG_CANCER              0.190451     1.000000

In [10]:
data_new['ANXYELFIN'] = data_new['ANXIETY']*data_new['YELLOW_FINGERS']
data_new

YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  FATIGUE   \
0                 1        1              0                0         1   
1                 0        0              0                1         1   
2                 0        0              1                0         1   
3                 1        1              0                0         0   
4                 1        0              0                0         0   
..              ...      ...            ...              ...       ...   
304               0        0              1                1         1   
305               0        0              0                0         1   
306               0        0              0                0         0   
307               0        1              0                0         1   
308               0        0              1                0         1   

     ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY  \
0           0         1                  1         1                      1   
1           1         0                  0         0                      1   
2           0         1                  0         1                      0   
3           0         0                  1         0                      1   
4           0         1                  0         1                      0   
..        ...       ...                ...       ...                    ...   
304         0         0                  1         1                      1   
305         1         1                  1         1                      0   
306         1         1                  1         1                      0   
307         1         0                  1         1                      0   
308         1         1                  1         0                      1   

     CHEST PAIN  LUNG_CANCER  ANXYELFIN  
0             1            1          1  
1             1            1          0  
2             1            0          0  
3             1            0          1  
4             0            0          0  
..          ...          ...        ...  
304           0            1          0  
305           1            1          0  
306           1            1          0  
307           1            1          0  
308           0            1          0  

[309 rows x 13 columns]

In [11]:
X = data_new.drop('LUNG_CANCER', axis = 1)
y = data_new['LUNG_CANCER']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [13]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)
print(X_test)

(247, 12) (247,)
(62, 12) (62,)
     YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  CHRONIC DISEASE  FATIGUE   \
63                0        1              0                1         0   
231               1        1              1                0         1   
167               0        0              0                1         0   
159               0        1              1                1         0   
189               1        1              1                0         1   
..              ...      ...            ...              ...       ...   
34                1        1              0                0         0   
250               1        1              1                0         1   
33                1        1              0                1         0   
21                1        1              1                0         0   
103               1        1              1                1         0   

     ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY  \


In [14]:
from sklearn.svm import SVC
svm = SVC(kernel = 'linear', random_state=0)
svm.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

In [15]:
pred = svm.predict(X_test)

In [16]:
pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [17]:
from sklearn import metrics
metrics.accuracy_score(y_test, pred)

0.9193548387096774

In [18]:
confusion_matrix(y_test, pred)

array([[ 6,  4],
       [ 1, 51]], dtype=int64)

In [34]:

from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, pred, average='weighted')

(0.9159614578969417, 0.9193548387096774, 0.9133696288283176, None)

In [19]:
rbf_svm = SVC(kernel = 'rbf', random_state=0)
rbf_svm.fit(X_train, y_train)
rbf_pred  = rbf_svm.predict(X_test)
rbf_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [20]:
accuracy_score(y_test, rbf_pred)

0.9032258064516129

In [21]:
confusion_matrix(y_test, pred)

array([[ 6,  4],
       [ 1, 51]], dtype=int64)

In [33]:

from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, pred, average='weighted')

(0.9159614578969417, 0.9193548387096774, 0.9133696288283176, None)

In [24]:
poly_svm = SVC(kernel = 'poly', random_state=0)
poly_svm.fit(X_train, y_train)
poly_pred  = poly_svm.predict(X_test)
print(poly_pred)
print(accuracy_score(y_test, poly_pred))
confusion_matrix(y_test, pred)

[1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 1 0 1 1 1 1]
0.967741935483871


array([[ 6,  4],
       [ 1, 51]], dtype=int64)

In [32]:

from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, pred, average='weighted')

(0.9159614578969417, 0.9193548387096774, 0.9133696288283176, None)

In [25]:
sgm_svm = SVC(kernel = 'sigmoid', random_state=0)
sgm_svm.fit(X_train, y_train)
sgm_pred  = sgm_svm.predict(X_test)
print(sgm_pred)
print(accuracy_score(y_test, sgm_pred))
confusion_matrix(y_test, sgm_pred)

[1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.8064516129032258


array([[ 1,  9],
       [ 3, 49]], dtype=int64)

In [35]:

from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(y_test, pred, average='weighted')

(0.9159614578969417, 0.9193548387096774, 0.9133696288283176, None)